name: Android Build 

on:

  push: 
    branches: ['master']

 
  pull_request:
    branches: ['master']


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/checkout@v4
        with:
         distribution: 'temurin'
         java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew assembleDebug

      - name: Run unit test
        run: ./gradlew testDebugUnitTest
